# Generated by Django 4.2 on 2024-05-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='ingrediente',
            field=models.TextField(default=''),
        ),
    ]
